### PR TITLE
Removed timezone trim as some systems may require it although it's optional

### PR DESCRIPTION
**Pull request by carnau**
Related to: https://github.com/goetas-webservices/xsd2php-runtime/issues/4

### CODE REVIEW

**Comment by carnau** [comment]
Forgot to edit the unit tests, will come soon

**Comment by carnau** [comment]
Hello @goetas ,

Any plan on merge this PR anytime soon?

Regards

**Comment by goetas** [comment]
can you explain a bit your use case?

**Comment by carnau** [comment]
I'm working against a SAP implementation which does not process OTA messages that doesn't provide the timezone.

**Comment by goetas** [comment]
im testing your pr against a ota test suite i had...

**Comment by goetas** [comment]
alright!

**Pull request merged**
